networks:
  dev:

version: '3.9'
services:
  mysql:
    image: mariadb:latest
    env_file:
      - ./.env
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dev


  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis
      - mysql
    ports:
      - "8010:8000"
    networks:
      - dev
    volumes:
      - .:/app

#volumes:
#  db_data: